### ISSUE TITLE
support for converting configuration values to API values

### ISSUE THREAD

**Issue by codingchili** [codingchili/lifx-circadian#1]
Example

```yaml
default_color:
      # hue
    - 0xCBCB
      # saturation
    - 0xFFFF
      # brightness
    - 0xAFFF
      # kelvin.
    - 2500
```

- This isn't too readable, please use 0xRRGGBB or (R, G, B) where {R,G,B} => 0..255
- Saturation should be 0..1
- Brightness should be 0..1
- Kelvin left as-is.

Convert these values when parsing the configuration.

Also apply to
- Default color

**Comment by codingchili** [comment]
done, now looks like this

```yaml
    - name: "LIFX Flory"
      schema:
          - power: True
            brightness: 0.5
            saturation: 1.0
            transition: 60
            hue: 299
            cron: "49 19 * * * 0"
```
